/control/alias G4EPP_BUILD_DIR /Users/luna/Documents/Work/Research/geant4/G4EPP-build # Do not include a slash at the end

/control/alias INITIAL_ALTITUDE_KM 450.0 # Starting altitude of particles in the simulation
/control/alias NUMBER_OF_PARTICLES 100


# TODO allow user to change -- probably want them to be command line arguments
# fWarningEnergy # Particles below this energy are killed after 1 step. Value arbitrary 
# fImportantEnergy # Particles above this energy are killed after fNumberOfTrials if they are looping. Value arbitrary 
# fNumberOfTrials # Number of trials before a looping 'important' particle is killed?. Value arbitrary. Set very high to avoid losing particles
# particle type, e- p+ gamma
# collection altitude


/control/echo Executing Run: {BEAM_ENERGY_KEV} keV, {BEAM_PITCH_ANGLE}º...

# ??????
# Set low energy EM processes, including fluorescence
#/process/em/fluo true
#/process/em/auger false
#/process/em/augerCascade false
#/process/em/pixe true
#/process/em/deexcitationIgnoreCut false
#/cuts/setMaxCutEnergy 50 eV

# Set file name for atmosphere table
/dataCollection/setAtmosFileName MSISE00_atmosphere.csv 

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/particle/verbose 0
/geometry/navigator/verbose 0
/process/had/verbose 0

/run/initialize

/field/setStepperType 10 # 10 - RungeKutta w/ PrinceDormand method, 7-8

# 0 - electrons
# 1 - solar X-ray spectrum
# 2 - CXB (Cosmic X-ray Background)
/energy/setSourceType 0

# Bremsstrahlung splitting
/process/em/setSecBiasing eBrem world 100 100 MeV

# Set result filepaths
/control/alias RESULTS_DIR {G4EPP_BUILD_DIR}/results
/control/alias BEAM_PARAMETERS {BEAM_ENERGY_KEV}keV_{BEAM_PITCH_ANGLE}deg_{NUMBER_OF_PARTICLES}electrons

/dataCollection/setEnergyDepositionFileName {RESULTS_DIR}/energy_deposition_{BEAM_PARAMETERS}.csv
/dataCollection/setBackscatterFilename {RESULTS_DIR}/backscatter_{BEAM_PARAMETERS}.csv

# Set beam parameters
/energy/setFoldingEnergy {BEAM_ENERGY_KEV} # [keV]
/energy/setMaximumPitchAngle {BEAM_PITCH_ANGLE}  # [deg]
/energy/particleStartingAltitude {INITIAL_ALTITUDE_KM}

# Execute run
/control/echo Executing Run: {BEAM_ENERGY_KEV} keV, {BEAM_PITCH_ANGLE}º...
/run/beamOn {NUMBER_OF_PARTICLES}