/control/alias NUMBER_OF_PARTICLES 10 # TODO 1e5
/control/alias G4EPP_BUILD_DIR /Users/luna/Documents/Work/Research/geant4/G4EPP-build # Do not include a slash at the end

/control/echo Executing Run: {BEAM_ENERGY_KEV} keV, {BEAM_PITCH_ANGLE}º...


# ??????
# Set low energy EM processes, including fluorescence
#/process/em/fluo true
#/process/em/auger false
#/process/em/augerCascade false
#/process/em/pixe true
#/process/em/deexcitationIgnoreCut false
#/cuts/setMaxCutEnergy 50 eV

# Set file name for atmosphere table
/dataCollection/setAtmosFileName MSISE00_atmosphere.csv 

/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/field/setStepperType 10 # 10 - RungeKutta w/ PrinceDormand method, 7-8

# 0 - electrons
# 1 - solar X-ray spectrum
# 2 - CXB (Cosmic X-ray Background)
/energy/setSourceType 0

# Bremsstrahlung splitting
/process/em/setSecBiasing eBrem world 100 100 MeV

# Set result filepaths
/dataCollection/setHistFileName spectra{BEAM_ENERGY_KEV}keV_{BEAM_PITCH_ANGLE}deg.csv
/dataCollection/setBackscatterFilename {G4EPP_BUILD_DIR}/results/backscatter_{BEAM_ENERGY_KEV}keV_{BEAM_PITCH_ANGLE}deg_{NUMBER_OF_PARTICLES}electrons.csv

# Set beam parameters
/energy/setFoldingEnergy {BEAM_ENERGY_KEV} # [keV]
/energy/setMaximumPitchAngle {BEAM_PITCH_ANGLE}  # [deg]
/energy/particleStartingAltitude 450.0  # [km A1B]

# Execute run
/control/echo Executing Run: {BEAM_ENERGY_KEV} keV, {BEAM_PITCH_ANGLE}º...
/run/beamOn {NUMBER_OF_PARTICLES}